### ISSUE TITLE
Dungeons are overpopulated, enough to lag and then freeze the game

### ISSUE THREAD

**Issue by d4goxn** [Greymerk/minecraft-roguelike#101]
I've been building a base on top of a dungeon, and occasionally venturing into it. Unfortunately, there are so many mobs that I can't push through them. This is probably because there seems to be a huge number of spawners; I'm finding another spawner every dozen blocks or so as I explore in creative mode. As the mob population increases, the frame rate slows to a crawl.

Is there any way to reduce the number of spawners, to maybe 1-6 on each dungeon level? I'm not seeing any parameter that obviously controls spawner frequency in the config docs.

An even better solution would be to check that the mob population in the loaded chunks is < 200 before spawning a new wave of mobs. This would ensure that they don't build up in a confined space.

Minecraft: 1.11.2
Roguelike Dungeons: 1.6.2
Nice comp, much ram, many cores.

**Comment by Greymerk** [comment]
> there are so many mobs that I can't push through them

Just as a general tip for minecraft, don't forget you can just walk away from an area and all the mobs will naturally despawn. It's a dirty trick, but handy for situations like that.

> the frame rate slows to a crawl.

This really shouldn't be happening normally. It sometimes happens depending on other mods which affect entities. I usually don't see it happen and my computer is pretty underpowered by today's standards.

> Is there any way to reduce the number of spawners, to maybe 1-6 on each dungeon level?

Currently, there's no simple way to do that. Maybe at some point there will be, but i'll have to give a lot of thought to how to design it sensibly if i do attempt to add such a feature.

> An even better solution would be to check that the mob population in the loaded chunks is < 200 before spawning a new wave of mobs. This would ensure that they don't build up in a confined space.

It's unlikely something like this will ever happen, because I don't attempt to control what happens in terms of game mechanics, I am only concerned with worldgen. They're just vanilla spawners with vanilla mechanics.

**Comment by Syndaryl** [comment]
As a first draft, I'd accept being able to set a %age chance for each spawner - so if it's 50%, then roughly half of the expected spawners would exist.

The tomb levels are pretty brutal for me sometimes until I can get enough torches in or spawners broken. Having to run away, wait for everything to despawn, then SPRINT back down to spam some more torches and then run away for a while is... bleh.

**Comment by BionicFelps** [comment]
I like that the dungeons get very hard personally, but I can make something like this happen in version 1.5.9

It's a kitchen sink modpack so obviously I can't narrow it down to roguelike, I'll try placing some creative spawners and reproducing... Basically, after a death the entity count climbs like crazy into the thousands. Logging out and back in returns mechanics to normal.

**Comment by BionicFelps** [comment]
Normal spawners don't cause it (at least ones spawning pigs)

**Comment by Syndaryl** [comment]
It's not an issue of of "hard", it's an issue of "my computer is crushed under the load of monsters and reduced to smouldering rubble". It's hard because I get a framerate of approximately once every four seconds :P
