### ISSUE TITLE
when assigning rooms other rooms still appear

### ISSUE THREAD

**Issue by resinate** [Greymerk/minecraft-roguelike#106]
when i made the room layout for certain rooms to spawn, rooms like cake rooms still spawn

**Comment by Greymerk** [comment]
This is an issue I'm attempting to address in some of the latest pre-release versions. It's related to implicit inheritance, which turned out to be difficult to work with.

Moving forward it'll be necessary to explicitly inherit from the built-in settings you want, and you can leave out those which you want to change, such as the rooms.

**Comment by resinate** [comment]
u can delete or close this ur newest update on project site fixed this
