### ISSUE TITLE
Server Error on Dungeon Gen

### ISSUE THREAD

**Issue by yepidoodles** [Greymerk/minecraft-roguelike#115]
Sometimes when Dungeons generate, I get these massive amounts of errors in the console which lag the server down until they end.

https://pastebin.com/Vqff5K2e

It's basicly this error 10's, maybe 100's of times. I know the error also includes Pam's Harvestcraft and Quark, however they are no longer updating to 1.10.2, so pointless to see if they can fix it.

SpongeForge: 1.10.2-2281-5.2.0-BETA-2274
Forge: 2254
Roguelike Dungeons: 1.5.9

**Comment by Greymerk** [comment]
I don't know anything about Sponge, and I don't feel that it's my responsibility to. Unless someone can point out a specific thing I've done incorrectly I'm not going to attempt to understand what went wrong here.

Since this doesn't happen in forge, I can only assume it's an incompatibility with sponge, or undefined behavior somewhere.
