### ISSUE TITLE
Mobs spawning clientside

### ISSUE THREAD

**Issue by ssblur** [Greymerk/minecraft-roguelike#125]
On version 1.11.2-1.6.6. Some mobs will spawn exclusively on the client side, causing the amount of entities to grow and not go back down. Such entities, as they are not tracked by the server, will not despawn when slain or when changing difficulty, and can cause intense lag for clients.

Cause unknown at the time of posting. Mod list can be provided if necessary.

**Comment by BionicFelps** [comment]
Related:
https://github.com/Greymerk/minecraft-roguelike/issues/101

**Comment by BionicFelps** [comment]
Steps to reproduce:
1) Join multiplayer server
2) Find a roguelike
3) Die inside
4) Respawn (preferably inside)
5) Look at entity count raising at an alarming rate.

**Comment by Insane-96** [comment]
Can confirm in latest version

**Comment by Greymerk** [comment]
I suspect that what's going on is i haven't been checking whether the spawner code is running in the remote world (the client). If that's the case then I just need to add that check in and then these client side entities won't get created.

It never occured to me that this event would be firing client side, but sort of makes sense.

**Comment by Greymerk** [comment]
This version should no longer have this issue, if you'd like to try it out to confirm.
[https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.7.3](url)

**Comment by Insane-96** [comment]
Any plank on fixing this in 1.11 too?

**Comment by DChronosX** [comment]
Would like to ask if you could please implement this bug fix and any others into the 1.7.10 version of your awesome patch.  As others here said, I tested things by changing the rogueSpawners to false and now things are very playable.  I was able to explore an entire dungeon top to bottom and back out again, allowing everything to spawn in a few different dungeons (in creative mode so I could do so in a decent timeframe), spent about an hour and a half exploring and testing, things are going well now... but still would like those bug fixes so those of us on our server can enjoy the full extent of this mod.

Thank you in advance if you could... at the very least, if you could implement these specific bugfixes in the "fixed in dev" link above, it would be nice.
