### ISSUE TITLE
Server side only

### ISSUE THREAD

**Issue by JamieKG** [Greymerk/minecraft-roguelike#13]
Hi can you still run this mod server side only like you used to I added it to my server and my client is rejected due to not having the mod

Thanks JamieKG

**Comment by Greymerk** [comment]
The issue is that I can't publish the source for the server side only "jar mod" without publishing mojang code with it. I stopped posting that version since there was very little demand for it anyway, and it required extra work on my end.

If you really want the jar version for a modded vanilla server then best to ask me about it privately. or via twitter or something. I have no plans of publicly publishing it anymore... unless something in the modding scene radically changes.

**Comment by JamieKG** [comment]
ok thanks for the response it was just that the forge server side only was easier then having all the clients install it in there mod packs

**Comment by goldbondx** [comment]
I would agree..this is a fantastic addon for forge and I would like to run this server side. I will try to contact you.
