### ISSUE TITLE
Question on Loot

### ISSUE THREAD

**Issue by katur239** [Greymerk/minecraft-roguelike#18]
What dungeon loot tables are drawn from when chests are placed? I'm just finding 99.9% of all chests will only have Vanilla items, very rarely I'll find a mod item (usually a single unknown dimlet from RFTools) in a chest.

**Comment by phase5** [comment]
Hi,

You can customize the loot that is placed in your dungeon chests in the config files.
You have to create the files for this in the settings folder. (which you also have to create - it does not exist by default)

Have a look in the Wiki at the "Loot Customisation" section.

**Comment by Greymerk** [comment]
I created my own loot system for the mod. Included in the chest loot is the Forge DungeonLoot hook which is used to fill regular dungeon chests. The only modded stuff you'll find in the chests is what's added using the forge hook.

If you want to customize the loot then you'll need to create custom settings for it. There's no table like a spreadsheet, the loot is procedurally generated.

**Comment by Artur58** [comment]
How do you do that?

**Comment by Greymerk** [comment]
This is no longer true as of roguelike dungeons 1.8.0. There's now i way to add loot tables to chests through settings. No tutorial yet, but i added an example setting to my demo repo.
https://github.com/Greymerk/rd-settings/blob/master/loot_tables.json
documentation lives here:
https://github.com/Greymerk/minecraft-roguelike/wiki/Loot-Rules#loot-table

For further questions please create a new issue instead of posting in an old one.
