### ISSUE TITLE
[Suggestion] Automatically pull from various loot injects

### ISSUE THREAD

**Issue by cybercat5555** [Greymerk/minecraft-roguelike#199]
As it says on the title. Roguelike Chests should also draw from new loots added by other mods, in order to make exploring them more rewarding, rather than having to manually add them all.

**Comment by Korumaku** [comment]
I'd love for this feature to be added. I've been working on trying to configure the loot dungeon tables specifically because items from other mods weren't showing up properly, but it seems that the loot table settings aren't working properly. From what I've seen online many people seem to be having lots of trouble getting it to work as well. Automatically adding in loot tables including modded items would solve that quite nicely.

**Comment by srwaggon** [comment]
@cybercat5555 
@Korumaku 
I ended up adding this in a fork:
https://www.curseforge.com/minecraft/mc-mods/roguelike-dungeons-fnar-edition
