### ISSUE TITLE
Max and min height in settings does not to seem to change dungeon location

### ISSUE THREAD

**Issue by Drakkett** [Greymerk/minecraft-roguelike#44]
In testing for TFC version, noticed that updating the max and min height settings does impact the towers actually showing up but the dungeon always seems to spawn the first level at 50.  Is there a settings config or settings override that we can utilize to change this?   I figure this impacts both standard RLD and the TFC conversion I am doing, so opened it as a new issue.

Thanks!!

Drakkett

**Comment by Greymerk** [comment]
All my settings assume there's exactly 5 levels, always. So shifting the dungeon upward would just result in having less dungeon toward the bottom of the world. In standard world generation the dungeon fits correctly.

A lot of things would need to be changed in order to support worlds with a thicker ground layer, and it's outside the scope of what I designed the mod for in the first place.

That's the reason in a nutshell. Someone else made a pull request introducing those min/max values as config settings. I consider them vestigial at this point and not very interesting.

Maybe at some point i'll look at supporting options for dungeons at variable depths, but it's never seemed important enough to tackle.

**Comment by Drakkett** [comment]
I've figured out how to move the dungeons, only issue I've found so far was the loot level settings and I put that as a new issue.  Going to close out this one.

Thanks,

Drakkett
