### ISSUE TITLE
[1.10.2] Spawner reverts back to original after 1 use

### ISSUE THREAD

**Issue by jmcaffee** [Greymerk/minecraft-roguelike#61]
I change (with an Actually Additions spawner changer) a spider spawner found in a Roguelike Dungeon to enderman spawner, it spawns one enderman, then reverts back to spider spawner. This is in the overworld.

The spawner was captured/moved using a Mekanism cardboard box.

As part of further testing (see [ActuallyAdditions/issues/162](https://github.com/Ellpeck/ActuallyAdditions/issues/162) ) it seems this may only affect spawners from Roguelike Dungeons. When the spawner is changed with a Spawn egg, the same thing occurs.

When a spawn egg is applied to a minecraft spawner pulled in with the `/give` command, the spawn remains as the changed type.

**Comment by Greymerk** [comment]
Is there a walkthrough or tutorial you can link me to on how you're using the mod to do this? would have to try it for myself.

Anyway, the short story is that I use a vanilla minecraft feature created for map-makers called custom spawner metadata. It's an NBT structure you can attach to a spawner to give information about the spawned mob. The reason I have to do this is so that only the dungeon's spawners will be equipped with special equipment, it also provides information about what quality of gear the monsters will spawn with.

Whatever mod tool you're using needs to have a way to clear the custom spawner metadata. Probably what it does it assigns a value to the "next" mob, and then after that first one minecraft reassigns "next" to be one pulled from custom spawner metadata. This is all vanilla spawner mechanics, but probably rarely used by mods.

If you have some tool that can move a spawner without preserving NBT data that might do the trick. You'll probably wind up with a pig spawner which you can then do whatever you want with.

**Comment by jmcaffee** [comment]
Yes, this sounds similar.

Using the All The Mods mod pack:

- I'm grabbing a spider spawner from a Roguelike Dungeon with a Mekanism cardboard box
- after placing the boxed spawner 3 blocks above the middle of a TiCon smeltery, I unpack the box (shift right click)
- then using a Actually Additions spawner changer (containing an Enderman) on it to change it to an Enderman spawner
- The spawner spawns a single enderman, then reverts to a spider spawner.

**Comment by Greymerk** [comment]
Again, that's due to vanilla spawner mechanics. What happens is if there's no custom spawner NBT data then it recycles the "next" thing to spawn. If there is custom spawner NBT data then it grabs the "next" mob from that source. It's not really bug, it's just a quirk in how vanilla spawners work.
