### ISSUE TITLE
massive lag and low fps reaching the bottom of roguelike dungeons

### ISSUE THREAD

**Issue by lightning02** [Greymerk/minecraft-roguelike#64]
as the in the title, I and other friends encountered massive lag and freezes even while around the roguelike complex, if you go deeper is even worst.
I thought the mobs was the cause, but even using /butcher (radius) the problem remain.. my first impression was that the spawners itself make the game lagging a bit..
the modpack we're using is this one (http://www.technicpack.net/modpack/rise-of-humanity-ultra-lite.872978/changelog/319533)

**Comment by guachitonico** [comment]
I can confirm, I'm running the modpack All The Mods and it's basically unplayable at that point, I run my own server with max 4GB and I allocate 5G to minecraft, The server lags insanely and it cripples my fps in minecraft.

**Comment by Cuppycake** [comment]
On our server we are noticing this happens when a creeper explodes in the dungeon. It causes an infinite explosion loop. TPS instantly drops to 1 and remains there. Only fix we found is to world edit the region or delete the regions .mca file completely.

**Comment by Greymerk** [comment]
It has to be a mod interaction causing these issues because there's just not enough going on in the dungeon outside of the initial dungeon generation.

My troubleshooting advice would be to try removing the mod and see if this changes anything. I have personally never seen this happen, and I run the mod with far less allocated memory.
