### ISSUE TITLE
(1.7.10) Custom spawner config not working(no console errors shown)

### ISSUE THREAD

**Issue by Zero-ui9** [Greymerk/minecraft-roguelike#65]
My config : http://pastebin.com/visjwrxi
As far as I can tell from the wiki, I have everything formatted correctly, yet the game acts as if I havn't even made that config at all and nothing changes. Furthermore, there are no console errors whatsoever, so even if I did get something wrong, I have no way of knowing(console errors have indeed came up when I screwed up other stuff when I was working on themes).

As a (slightly unrelated) side note, the lack of control over the spawner's nbt is kind of disappointing. I would very much like it if I could control things like spawn range/player range, entity count, or spawn delay, all of which can be done with a /setblock command. It would be even better if I could make a specific spawner(or all the spawners on a floor) ignore light level. Then theoretically, you could have a dungeon with very few spawners overall, but just have those spawners be able to reach the entire floor(of course that might require being able to implement custom rooms, which could be possible by having a MCedit schematic file of the room and then some JSON describing where the openings are to that room and whether to rotate it or not)Of course its understandable if you wouldn't want to bother doing something like that for 1.7.10 but it would still be pretty awesome.

**Comment by Zero-ui9** [comment]
After a bit more looking around on the wiki, I think I might have the config correct now http://pastebin.com/K0wayabm
however the previous problems still remain. It does absolutely nothing, and the console refuses to give any input about it. (and yes I've got the folders in the correct load order and that sorta stuff) 
http://puu.sh/qLIqs/0093d22016.png
http://puu.sh/qLIsR/9dfe4fedd8.png

**Comment by Greymerk** [comment]
The spawner configs are really unpolished.

I've put a lot of work into the way the chests are handled, and it may be worth reworking the way Spawners are done.

Your point about console errors is true, it might actually make sense at some point to implement a logging system for the mod specifically, to output detailed information about what happened when a specific dungeon was spawned. Up until now I've just been blindly poking at the configs, and I agree it's a bit frustrating.

Regarding the spawner settings, yes, I can add controls for spawner mechanisms like range, etc. As well as NBT. I'll keep this issue here as a reminder.

**Comment by EnderStar** [comment]
I see in the wiki that is possible to add nbt to the spawners but is the nbt added to the mobs or the mobspawner block? And how is the format to add the nbt? I tryed to add it like in minecraft:
 `				"BLAZE" : [
					{
					"name" : "Blaze",
					"meta" : {
						"SpawnData" : {
							"Attributes" : [
								{
								"Name" : "generic.maxHealth",
								"Base" : "100.0"
								}
							]
								}
						}
					}
				]`
But it doesnt work
