### ISSUE TITLE
Dungeons Not Reflecting Edited Files After a /roguelike config reload

### ISSUE THREAD

**Issue by Alan19** [Greymerk/minecraft-roguelike#82]
When I reload the configs, when I use /roguelike dungeon here without specifying a dungeon, the dungeon spawned do not reflect the contents of the changed .json file(s). Reloading Minecraft does work but it takes a long time in a big modpack.

**Comment by EnderStar** [comment]
How do you do to speify a name, it always tells me that the name wasnt found

**Comment by Alan19** [comment]
That usually means there's an error and it usually says which file is wrong in the logs.

**Comment by Greymerk** [comment]
I'll look into the reload issue. It should reload all those settings.

name refers to the name field in the json object. "name" : "mysetting"

**Comment by Greymerk** [comment]
Ahh ok. You're right. Currently the way it works is that the settings are automatically reloaded when you spawn a dungeon by setting name.

"roguelike settings reload" is for the settings.

Generally speaking when I've been working on settings json files I have just been spawning the dungeons by name. That's why I set it up like that. But you're probably right, the config reload should probably also reload the settings.
